### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by okawashotaro** [ShotaroOkawa/furima_28755#9]
### フリマアプリのURL
- https://furima-28755.herokuapp.com/
### Basic認証のIDとパスワード
- ID: shotaro
- パスワード: password
### 出品者用のメールアドレスとパスワード
- seller@gmail.com
- password123
### 購入者用のメールアドレスとパスワード
- purchaser@gmail.com
- password123
### 購入用カードの番号・期限・セキュリティーコード
- 番号: 4242424242424242
- 期限: 1/21
- セキュリティーコード: 123

**Comment by tanakayuumi** [comment]
ShotaroOkawaさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
